	.INSERT "ZORK2FREQ"
	.INSERT "ZORK2DAT"			; DATA IS IN THIS FILE
	.INSERT "GMACROS"
	.INSERT "GSYNTAX"
	.INSERT "2DUNGEON"
	.INSERT "GGLOBALS"
	.INSERT "GCLOCK"
	.INSERT "GMAIN"
	.INSERT "GPARSER"
	.INSERT "GVERBS"
	.INSERT "2ACTIONS"
	.INSERT "ZORK2STR"
	.END
