

; STRINGS ARE DEFINED HERE

STRBEG::

	.GSTR STR?1,"You are inside an ancient barrow hidden deep within a dark forest. The barrow opens into a narrow tunnel at its southern end. You can see a faint glow at the far end."
	.GSTR STR?2,"You may not recall, but when you entered, the door of the barrow shut behind you. There is no way out."
	.GSTR STR?3,"You are standing at the southern end of a narrow tunnel where it opens into a wide cavern. The cavern is dimly illuminated by phosphorescent mosses clinging to its high ceiling. A deep ravine winds through the cavern, with a small stream at the bottom. The walls of the ravine are steep and crumbly. A foot bridge crosses the ravine to the south."
	.GSTR STR?4,"As you start down, you slip on the crumbling rocks and pull back, narrowly averting a fatal fall."
	.GSTR STR?5,"You are standing on a crude but sturdy wooden foot bridge crossing a deep ravine. The path runs north and south from here."
	.GSTR STR?6,"The drop would be fatal."
	.GSTR STR?7,"You'll have to specify a direction."
	.GSTR STR?8,"This is the center of the great cavern, carved out of the limestone. Stalactites and stalagmites of many sizes are everywhere. The room glows with dim light provided by phosphorescent moss, and weird shadows move all around you. A narrow path winds southwest among the stalagmites, and another leads northeast."
	.GSTR STR?9,"You are at the southern edge of a great cavern. To the south across a shallow ford is a dark tunnel which looks like it was once enlarged and smoothed. To the north a narrow path winds among stalagmites. Dim light illuminates the cavern."
	.GSTR STR?10,"This is a dark tunnel with dim light to the northeast. The tunnel is smooth but dusty and filled with twigs and leaves, debris which becomes deeper as the tunnel branches into a wide corridor leading southwest and a narrower one leading southeast."
	.GSTR STR?11,"There is a beautiful unicorn here cropping grass."
	.GSTR STR?12,"This is the northern end of a formal garden. Hedges hide the cavern walls, and if you don't look up, the illusion is of a cloudy day outside. The light comes from a large growth of glowing mosses on the roof of the cave. A break in the hedge is almost overgrown to the north. A carefully manicured path leads south. In the center of a rosebed is a small open structure, painted white. It appears to be a gazebo."
	.GSTR STR?13,"This is a gazebo in the midst of a formal garden. It is cool and restful here. A tea table adorns the center of the gazebo."
	.GSTR STR?14,"This is the middle part of a formal garden. Hedges hide the cavern walls and a dim illumination comes from mosses far above. The path is of small crushed white stones. It winds among bushes and flower beds from south to north. To the north a small structure can be seen. To the south are peculiarly shaped bushes. There is a small gap in the hedges to the west."
	.GSTR STR?15,"This is the southern end of a formal garden. Hedges hide the cavern walls and mosses provide dim illumination. Fantastically shaped hedges and bushes are arrayed with geometric precision. They have not recently been clipped, but you can discern creatures in the shapes of the bushes: There is a dragon, a unicorn, a great serpent, a huge misshapen dog, and several human figures. On the west side of the garden the path leads through a rose arbor into a tunnel."
	.GSTR STR?16,"The path follows the south edge of a deep ravine and heads northeast. A tunnel heads southwest, narrowing to a rather tight crawl. A faint whirring sound can be heard in that direction. On the east is a ruined archway choked with vegetation."
	.GSTR STR?17,"The ravine is extremely deep. You would never make it."
	.GSTR STR?18,"This is an arched hall of fine marble. The hall stops abruptly to the north at a ford across a stream, where the marble is cracked and broken. Perhaps a flood or collapse of the cave was responsible. To the south the hall opens into a large room. There is rather annoying whirring sound coming from that room."
	.GSTR STR?19,"That's a wall there."
	.GSTR STR?20,"You are fording the stream at a deep but not impossible spot. The water is very cold. The walls of the ravine rise to east and west. There is a small ledge along the north wall of the ravine. To the south is the entrance to a well-constructed but somewhat ruined hall."
	.GSTR STR?21,"The stream deepens rapidly, and you wisely return before drowning."
	.GSTR STR?22,"You notice that the ledge above would be a drier route west."
	.GSTR STR?23,"You are on a narrow ledge near the bottom of a deep ravine. The ledge continues to the west. A precarious climb up to another tiny ledge is possible. A short scramble down the rock face leads to a stream."
	.GSTR STR?24,"A ledge from the east ends here, and a tunnel leads north into the wall. There is a rather odd smokey odor in the warm air of the tunnel."
	.GSTR STR?25,"There are a lot of sharp rocks down there."
	.GSTR STR?26,"The room is a large cavern full of broken stone. The walls are scorched and there are deep scratches on the floor. A sooty dry smell is very strong here. A paved path winds from a large passage to the west, through the room, and across a huge stone bridge to the south. To the east a small crack is visible. A dark and smokey tunnel leads north."
	.GSTR STR?27,"The dragon hisses at you and blocks your way."
	.GSTR STR?28,"You are in the dragon's lair, where the rock walls are scarred by flame. A blackened doorway leads to the south."
	.GSTR STR?29,"A rotten old wooden chest is in one corner among the debris."
	.GSTR STR?30,"Nestled in the chest is a wrought gold statuette of a dragon."
	.GSTR STR?31,"A huge red dragon is lying on the rocks here, watching."
	.GSTR STR?32,"A huge red dragon is lying here, blocking the entrance to a tunnel leading north. Smoke curls from his nostrils and out between his teeth."
	.GSTR STR?33,"A huge dead dragon is lying half blocking the stream."
	.GSTR STR?34,"A beautiful young woman, wearing a dirty and bedraggled gown, sits on a rock in the corner. Her hair is unkempt and she is oblivious to your presence, almost in a trance."
	.GSTR STR?35,"A path leads east-west through a room decorated with beautiful frescoes of someone battling dragons and rescuing fair maidens. It is hard to tell who is doing this as those parts of the frescoes have been blackened and cracked by intense heat."
	.GSTR STR?36,"This is the middle of a ruined but still impressive stone bridge spanning a deep chasm. Water flows far beneath. A paved path leads north into a large open space. To the south, the path leads into a misty tunnel."
	.GSTR STR?37,"It's a long way down."
	.GSTR STR?38,"The room is cool and damp. The air is misty. A twisty path from the southeast splits here toward a wide northerly stone bridge, and a narrow westerly tunnel. It is from the latter that the mist and chill seem to originate."
	.GSTR STR?39," "
	.GSTR STR?40,"You don't even have an ice-pick."
	.GSTR STR?41,"You are in a tight chimney of solidified lava. It extends up at least another hundred feet and down to a large room far below. A large crack opens to the south, probably the result of a shift in the rock strata."
	.GSTR STR?42,"A winding corridor is filled with cobwebs. Some are broken and the dust on the floor is disturbed. The trend of the twists and turns is northeast to southwest. On the north side of one twist, high up, is a narrow crack."
	.GSTR STR?43,"This is a small chamber carved out of the rock at the end of a short crawl. On the wall is crudely chiseled the number ""8""."
	.GSTR STR?44,"You are trying to walk through an enormous rock."
	.GSTR STR?45,"This room looks like it was once a kennel for a very large dog (some of the bones would fit a dinosaur). It apparently hasn't been used for a long time, as the dust is fairly thick all over. The only exit is northeast."
	.GSTR STR?46,"A gigantic dog collar, large enough for three rhinoceros-sized dogs, is lying amidst the debris."
	.GSTR STR?47,"A long wooden club lies on the ground near the diamond-shaped window. The club is curiously burned at the thick end."
	.GSTR STR?48,"The words ""Babe Flathead"" are burned into the wood."
	.GSTR STR?49,"A marble stairway leads down into the gloom and a passage leads north."
	.GSTR STR?50,"A small room with oddly angled walls and passages in all directions."
	.GSTR STR?51,"This is the entrance to a huge crypt or tomb. A marble stairway leads up from a gateway arch."
	.GSTR STR?52,"The huge dog snaps nastily at you."
	.GSTR STR?53,"There is a vicious-looking dog guarding the entrance. It is more or less your usual dog, except that it has three heads and is the size of an elephant."
	.GSTR STR?54,"""Here lie the Flatheads, whose heads were placed on poles by the Keeper of the Dungeon for amazing untastefulness."""
	.GSTR STR?55,"This is the workshop of the Wizard of Frobozz."
	.GSTR STR?56,"This room is the Wizard's workroom. A hall continues east and west, and a larger room lies to the south. There are many shelves and racks on the walls, but the Wizard's workbench dominates the room. It is made of dark, heavy wood bound with iron. The workbench is stained from many years of use, and is deeply gouged as though some huge clawed animal was imprisoned on it. There are burn marks and even notes written in a crabbed hand. Many arcane items are scattered about the bench; alembics, mortar and pestle, small knives of various sizes, odd scraps of vellum, wax candles, and much more. In the center of a relatively clear area of the bench are affixed three stands - ruby, sapphire, and diamond - which form a triangle."
	.GSTR STR?57,"There is a strange black sphere here."
	.GSTR STR?58,"This is the Wizard's trophy room, filled with memorabilia of various sorts. On one wall is the Wizard's D. T. (Doctor of Thaumaturgy) degree from GUE Tech. Several old magic wands are mounted on a wand rack. A collection of dull and nicked swords testify to the fate of many foolhardy adventurers. Small bottles contain discarded homunculi (a few preserved in alcohol). There is a stuffed owl on a perch."
	.GSTR STR?59,"The text is in some obscure tongue. All that can be made out is a reference to ""sending in a matchbook cover."""
	.GSTR STR?60,"A hand-lettered label is affixed to the wall."
	.GSTR STR?61,"Warning!

The exhibits in this room are the property of the mighty Wizard of Frobozz (me), and are the fruits of diligent labor and study over many years. He who touches anything will regret it.

(signed)
Frobozz
"
	.GSTR STR?62,"Imbedded in the wall is an ornate trophy cabinet."
	.GSTR STR?63,"Shards of a smashed trophy case litter the room."
	.GSTR STR?64,"In this room, inscribed on the floor, is a great pentagram drawn with black chalk. In its center is a black circle."
	.GSTR STR?65,"Here a dark hallway turns a corner. To the south is a dark room, to the east is fitful light."
	.GSTR STR?66,"Filling the northern half of the room is a huge aquarium."
	.GSTR STR?67,"There is a clear crystal sphere lying in the sand."
	.GSTR STR?68,"There is a baby sea serpent swimming in the aquarium."
	.GSTR STR?69,"There is a dead sea serpent in a heap here."
	.GSTR STR?70,"The floor here seems to be made of sand, but it is hard to see anything else."
	.GSTR STR?71,"This is a former broom closet. The exits are to the east and west."
	.GSTR STR?72,"You are at the bottom of a large dormant volcano. High above you light enters from the cone of the volcano. The only exit is to the north."
	.GSTR STR?73,"You are about one hundred feet above the bottom of the volcano. The top of the volcano is clearly visible here."
	.GSTR STR?74,"You are about two hundred feet above the volcano floor. Looming above is the rim of the volcano. There is a small ledge on the west side."
	.GSTR STR?75,"You are high above the floor of the volcano. The rim of the volcano looks very narrow and you are very near it. To the east is what appears to be a viewing ledge, too thin to land on."
	.GSTR STR?76,"You are near the rim of the volcano. Above you it is open to the sky. To the west, there is a place to land on a wide ledge."
	.GSTR STR?77,"You are on a narrow ledge within an old dormant volcano. This ledge is about halfway between the floor below and the rim above. There is an exit to the south."
	.GSTR STR?78,"I wouldn't jump from here."
	.GSTR STR?79,"This must have been a large library, probably for the royal family. All of the shelves have been gnawed to pieces by unfriendly gnomes. To the north is an exit."
	.GSTR STR?80,"You are on a ledge in the middle of a large volcano. Below you the volcano bottom can be seen and above is the rim of the volcano. A couple of ledges can be seen on the other side of the volcano; it appears that this ledge is intermediate in elevation between those on the other side. The exit from this room is to the east."
	.GSTR STR?81,"I wouldn't try that."
	.GSTR STR?82,"It is impossible to cross this distance."
	.GSTR STR?83,"This is a small room, whose walls are formed by an old lava flow. There are exits here to the east and the south."
	.GSTR STR?84,"This is a large room full of assorted heavy machinery, whirring noisily. The room smells of burned resistors. Along one wall are three buttons which are, respectively, round, triangular, and square. Naturally, above these buttons are instructions written in EBCDIC. A large sign in English above all the buttons says
       ""DANGER -- HIGH VOLTAGE""
There are exits to the west and the south."
	.GSTR STR?85,"This is a dingy closet adjacent to a larger room to the north. Chiselled into a wall are these words:

     Protected by
       FROBOZZ
 Magic Alarm Company
  (Hello, footpad!)

There doesn't seem to be any footpad here, however."
	.GSTR STR?86,"You are trapped inside a solid steel cage."
	.GSTR STR?87,"You are at the top of the well. Well done. There are etchings on the side of the well. There is a small crack across the floor at the entrance to a room on the east, but it can be crossed easily."
	.GSTR STR?88,"It's a long way down!"
	.GSTR STR?89,"This is a damp circular room, whose walls are made of brick and mortar. The roof of this room is not visible, but there appear to be some etchings on the walls. There is a passageway to the west."
	.GSTR STR?90,"The walls cannot be climbed."
	.GSTR STR?91,"This is a small room containing a large oblong table, no doubt set for afternoon tea. It is clear from the objects on the table that the users were indeed mad. In the eastern corner of the room is a small hole (no more than four inches high). There are passageways leading away to the west and the northwest."
	.GSTR STR?92,"Only a mouse could get in there."
	.GSTR STR?93,"This is an enormous room, in the center of which are four wooden posts delineating a rectangular area, above which is what appears to be a wooden roof. In fact, all objects in this room appear to be abnormally large. To the east is a passageway. There are large gaping chasms to the west and northwest."
	.GSTR STR?94,"A great chasm blocks your way."
	.GSTR STR?95,"This is a large room, one half of which is depressed. Salty water flows from a large leak in the ceiling. The only exit is to the west."
	.GSTR STR?96,"This is the entrance hall of the Bank of Zork, the largest banking institution of the Great Underground Empire. A partial account of its history is in ""The Lives of the Twelve Flatheads,"" in the chapter on J. Pierpont Flathead. A more detailed history (albeit less objective) may be found in Flathead's outrageous autobiography ""I'm Rich and You Aren't - So There!"". Most of the furniture has been ravaged by passing scavengers. All that remains are two signs at the northwest and northeast corners of the room, which say:

    <--  VIEWING ROOMS  -->

The way out (ornate but tasteful) is to the east. "
	.GSTR STR?97,"This room was used by holders of safety deposit boxes to view their contents. On the north side of the room is a sign which says:

""Remain here while the teller retrieves your safety deposit box. When you are finished, leave the box, and exit to the south. Safety deposit boxes cannot be removed from this room!

Thank You for Banking at the Zork!"" "
	.GSTR STR?98,"This room was used by holders of safety deposit boxes to view their contents. On the north side of the room is a sign which says

""Remain here while the teller retrieves your safety deposit box. When you are finished, leave the box, and exit to the south. Safety deposit boxes cannot be removed from this room!

Thank You for Banking at the Zork!"" "
	.GSTR STR?99,"This is a small, bare room with no distinguishing features. There are no exits from this room."
	.GSTR STR?100,"This is the Vault of the Bank of Zork, in which there are no doors."
	.GSTR STR?101,"This is a large rectangular room. The east and west walls were used for storing safety deposit boxes, but all have been carefully removed by evil persons. To the east, west, and south of the room are large doorways. The northern ""wall"" of the room is a shimmering curtain of light. In the center of the room is a large stone cube, about 10 feet on a side. Engraved on the side of the cube is some lettering."
	.GSTR STR?102,"There is a curtain of light there."
	.GSTR STR?103,"This room was the office of the Chairman of the Bank of Zork. Like the other rooms here, it has been extensively vandalized. The lone exit is to the north."
	.GSTR STR?104,"There is a matchbook saying ""Visit ZORK I"" here."
	.GSTR STR?105,""">> Visit Exotic ZORK I <<

Consult the Frobozz Magic Travel Agency, or visit your local computer store for more details."""
	.GSTR STR?106,"There is a nervous Volcano Gnome here."
	.GSTR STR?107,"There is a blue label here."
	.GSTR STR?108," !! FROBOZZ MAGIC BALLOON COMPANY !!

Hello, Aviator!

To land your balloon, say LAND
Otherwise, you're on your own!

No warranty expressed or implied."
	.GSTR STR?109,"There is a square brick here which feels like clay."
	.GSTR STR?110,"The room is cluttered with debris from an explosion. The walls seem ready to collapse."
	.GSTR STR?111,"There is a balloon here, broken into pieces."
	.GSTR STR?112,"There is a card with writing on it here."
	.GSTR STR?113," Warning:
    This room was constructed over very weak rock strata. Detonation of explosives in this room is strictly prohibited!
         Frobozz Magic Cave Company
         per M. Agrippa, foreman
"
	.GSTR STR?114,"The excessively gaudy crown of Lord Dimwit Flathead sits in the safe."
	.GSTR STR?115,"Lord Dimwit's crown is here."
	.GSTR STR?116,"There is a beautiful red crystal sphere here."
	.GSTR STR?117,"There is a Stradivarius here."
	.GSTR STR?118,"A mass of ice fills the western half of the room."
	.GSTR STR?119,"A stoppered glass flask with a skull-and-crossbones marking is here. The flask is filled with some clear liquid."
	.GSTR STR?120,"There is a skull-and-crossbones engraved on the glass."
	.GSTR STR?121,"There is a green piece of paper here."
	.GSTR STR?122,"!!  FROBOZZ MAGIC ROBOT COMPANY  !!

 Hello, Master!

   I am a late-model robot, trained at GUE Tech to perform various simple household functions.

   To activate me, say the following:

        >ROBOT, <things to do>

At your service!"
	.GSTR STR?123,"There is a small hook attached to the rock here."
	.GSTR STR?124,"A strangely familiar brass lantern is lying on the ground."
	.GSTR STR?125,"There is a mangled steel cage here."
	.GSTR STR?126,"There is a pearl necklace here with hundreds of large pearls."
	.GSTR STR?127,"The icing spells out ""Eat Me."""
	.GSTR STR?128,"The leak has submerged the depressed area in a pool of tears. There is a hazy something at the deepest part of the pool."
	.GSTR STR?129,"On the floor is a priceless gold zorkmid (a valuable collector's item)."
	.GSTR STR?130,"There is an engraved zorkmid here."
	.GSTR STR?131,"This is a beautiful octagonal coin bearing the legends ""Ten Thousand Zorkmids"" and ""In Frobs We Trust""."
	.GSTR STR?132,"There is a Flathead stamp here."
	.GSTR STR?133,"This three zorkmid stamp bears a portrait of Lord Dimwit Flathead, ""Our Excessive Leader""."
	.GSTR STR?134,"A handsome book, bound in green leather, sits in the center of the room."
	.GSTR STR?135,"This book is written in a tongue with which I am unfamiliar."
	.GSTR STR?136,"Worn and battered in one corner of the room is a blue book."
	.GSTR STR?137,"Right beside the purple book sits a white one."
	.GSTR STR?138,"It is written in an unfamiliar tongue and details the use of various magical objects, chiefly the so-called ""magic wand"". Apparently these devices work by pointing them at the object to be ensorcelled, and then chanting the appropriate magic words. (It's truly amazing how credulous these ancients were, isn't it?)"
	.GSTR STR?139,"Lying in the dust, and covered with mold, is a purple book."
	.GSTR STR?140,"This book is written in a tongue with which I am unfamiliar. Assuming that one can indeed tell a book by its cover, it is likely filled with purple prose, the like of which is rarely seen outside the Great Underground Empire."
	.GSTR STR?141,"There is a robot here."
	.GSTR STR?142,"On the floor lies a moby ruby."
	.GSTR STR?143,"There is a moby ruby lying here."
	.GSTR STR?144,"There is a dented steel box here."
	.GSTR STR?145,"There is a solid steel cage in the middle of the room."
	.GSTR STR?146,"There is a package of candied goodies here."
	.GSTR STR?147,"There is a coil of black, braided string here."
	.GSTR STR?148,"There is a wooden bucket here, 3 feet in diameter and 3 feet high."
	.GSTR STR?149,"200 neatly stacked zorkmid bills are here."
	.GSTR STR?150,"On the floor sit 200 neatly stacked zorkmid bills."
	.GSTR STR?151,"Each bill is worth 100 zorkmids, and bears the legend ""In Frobs We Trust""."
	.GSTR STR?152,"The portrait of J. Pierpont Flathead is here."
	.GSTR STR?153,"A portrait of J. Pierpont Flathead hangs on the wall."
	.GSTR STR?154,"On the ground is a small, worn piece of paper."
	.GSTR STR?155,"The paper is barely readable. You can only make out ""... valuables are completely safe ... advanced magic technology ... impossible to take valuables from the depository ... either teller's ... Many customers faint ... teller pops in ... seems to walk through ... walls ..."""
	.GSTR STR?156,"There is a Gnome of Zurich here."
	.GSTR STR?157,"In the center of the table sits a blue crystal sphere."
	.GSTR STR?158,"** U.S. News and Dungeon Report **

FAMED ADVENTURER TO EXPLORE GREAT UNDERGROUND EMPIRE

Our correspondents report that a world-famous and battle-hardened adventurer has been seen in the vicinity of the Great Underground Empire. Local grues have been reported sharpening their (slavering) fangs....

""Zork II: The Wizard of Frobozz"" was written by Dave Lebling and Marc Blank, and is (c) Copyright 1981, 1982, 1983 by Infocom, Inc."
	.GSTR STR?159,"There is some water here."
	.GSTR STR?160,"There is a demon floating in midair here."
	.GSTR STR?161,"The Wizard of Frobozz is here, eyeing you warily."
	.GSTR STR?162,"An Elvish sword of great antiquity is here."
	.GSTR STR?163,"A sword of Elvish workmanship is on the ground."
	.GSTR STR?164,"A spray can is in the corner. In large type is the legend ""Frobozz Magic Grue Repellent""."
	.GSTR STR?165,"!!! FROBOZZ MAGIC GRUE REPELLENT !!!

Instructions for use: Apply liberally to creature to be protected. Duration of effect is unpredictable. Use only in place of death!

(No warranty expressed or implied)"
	.GSTR STR?166,"F"
	.GSTR STR?167,"If you insist.... Poof, you're dead!"
	.GSTR STR?168," it at the time."
	.GSTR STR?169,"Kicking the "
	.GSTR STR?170,"You should have looked before you leaped."
	.GSTR STR?171,"In the movies, your life would be passing before your eyes."
	.GSTR STR?172,"Geronimo..."
	.GSTR STR?173,"Playing in this way with the "
	.GSTR STR?174,"Pushing the "
	.GSTR STR?175,"Fiddling with the "
	.GSTR STR?176,"Very good. Now you can go to the second grade."
	.GSTR STR?177,"Are you enjoying yourself?"
	.GSTR STR?178,"Wheeeeeeeeee!!!!!"
	.GSTR STR?179,"Do you expect me to applaud?"
	.GSTR STR?180," hits you squarely in the head. Normally, this wouldn't do much damage, but by incredible mischance, you fall over backwards trying to duck, and break your neck, justice being swift and merciful in the Great Underground Empire."
	.GSTR STR?181,"Oh, no! You have walked into the slavering fangs of a lurking grue!"
	.GSTR STR?182,"Waving the "
	.GSTR STR?183,"  "
	.GSTR STR?184,"    "
	.GSTR STR?185,"      "
	.GSTR STR?186,"        "
	.GSTR STR?187,"          "
	.GSTR STR?188," doesn't seem to work."
	.GSTR STR?189," isn't notably helpful."
	.GSTR STR?190," has no effect."
	.GSTR STR?191," and devoured you!"
	.GSTR STR?192,"You can't swim in the dungeon."
	.GSTR STR?193,"Hello."
	.GSTR STR?194,"Good day."
	.GSTR STR?195,"Nice weather we've been having lately."
	.GSTR STR?196,"Goodbye."
	.GSTR STR?197,"A valiant attempt."
	.GSTR STR?198,"You can't be serious."
	.GSTR STR?199,"An interesting idea..."
	.GSTR STR?200,"What a concept!"
	.GSTR STR?201,"Look around."
	.GSTR STR?202,"Too late for that."
	.GSTR STR?203,"Have your eyes checked."
	.GSTR STR?204,"burning"
	.GSTR STR?205,"nestled"
	.GSTR STR?206,"The balloon floats majestically out of the volcano, revealing a breathtaking view of a wooded river valley surrounded by impassable mountains. In a clearing stands a white house. You drift into high winds, which carry you towards the snow-capped peaks. Oh, no! You crash into the jagged cliffs of the Flathead Mountains!"
	.GSTR STR?207,"ascends."
	.GSTR STR?208,"floats away. It seems to be ascending, due to its light load."
	.GSTR STR?209,"lifts off."
	.GSTR STR?210,"lands."
	.GSTR STR?211,"descends."
	.GSTR STR?212,"Now you've done it. It seems that the brick has other properties than weight, namely the ability to blow you to smithereens."
	.GSTR STR?213,"The way is blocked by debris from an explosion."
	.GSTR STR?214,"The room trembles and 5000 tons of rock fall on you, turning you into a pancake."
	.GSTR STR?215,"The ledge collapses, probably as a result of the explosion, and plummets to the ground far below. Sadly, you were still attached to the ledge."
	.GSTR STR?216,"The force of the recent explosion has caused the ledge to collapse."
	.GSTR STR?217,"The ledge has collapsed and cannot be landed on."
	.GSTR STR?218,"Although the Flatheads are dead, they foresaw that some cretin might tamper with their remains. Therefore, they took steps to punish such actions."
	.GSTR STR?219,"The crypt door squeaks open."
	.GSTR STR?220,"The crypt door squeaks closed."
	.GSTR STR?221,"The secret door opens noiselessly."
	.GSTR STR?222,"The secret door closes noiselessly."
	.GSTR STR?223,"The green curves begin to vibrate toward you, as if searching for something. One by one your possessions glow bright green. Finally, you are attacked by these magical wardens, and destroyed!"
	.GSTR STR?224,"If you insist."
	.GSTR STR?225,"That was delicious, but your dying memory is of feeling horribly dehydrated and thirsty."
	.GSTR STR?226,"The room seems to have become too small to hold you. The walls are not as compressible as your body, which is demolished."
	.GSTR STR?227,"You enter the pool, thrash around for a good while, and then drown. Sad, but true."
	.GSTR STR?228,"Noxious vapors prevent your entry."
	.GSTR STR?229,"As you pass out, you realize that the vapors from the flask's contents are fatal."
	.GSTR STR?230,"The entrance is blocked by sticky orange rubble. Probably some careless adventurer was playing with blasting cakes."
	.GSTR STR?231,"You have been blasted to smithereens (wherever they are)."
	.GSTR STR?232,"According to Prof. TAA of GUE Tech, the rapidly changing magnetic fields in the room are intense enough to electrocute you. I really don't know, but in any event, something just killed you."
	.GSTR STR?233,"According to Prof. TAA of GUE Tech, the magnetic fields in the room are intense enough to fry the delicate innards of the robot. I really don't know, but in any event, smoke pours from its ears and it has stopped moving."
	.GSTR STR?234,"There is a giant spark and you are fried to a crisp."
	.GSTR STR?235,"As the robot reaches for the sphere, a solid steel cage falls from the ceiling, trapping him. You can faintly hear his last words: ""Whirr, buzz, click!"" A cloud of smoke rising from beneath the cage confirms your fears about the fate of your brave mechanical friend."
	.GSTR STR?236,"You are stopped by a cloud of poisonous gas."
	.GSTR STR?237,"Time passes...and you die from some obscure poisoning."
	.GSTR STR?238,"A metallic voice says ""Hello, Intruder! Your unauthorized presence in the vault of the Bank of Zork has set off all sorts of nasty surprises, most of which are fatal. This message brought to you by the Frobozz Magic Vault Company."""
	.GSTR STR?239,"north"
	.GSTR STR?240,"south"
	.GSTR STR?241,"red"
	.GSTR STR?242,"blue"
	.GSTR STR?243,"white"
	.GSTR STR?244,"black"
	.GSTR STR?245,"The door is now open."
	.GSTR STR?246,"The door is now closed."
	.GSTR STR?247,"The lamp appears a bit dimmer."
	.GSTR STR?248,"The lamp is definitely dimmer now."
	.GSTR STR?249,"The lamp is nearly out."
	.GSTR STR?250,"You think it isn't?"
	.GSTR STR?251,"I think you've already done that."
	.GSTR STR?252,"You find yourself drawn toward the edge of the bridge. You peer over the side. Oops, that was clumsy of you! You tripped on something and fell in. Too bad."
	.GSTR STR?253,"For some odd reason you have tripped on your own feet, or perhaps an invisible cord stretched across the path. The resulting fall seems to have done you in."
	.GSTR STR?254,"dark"
	.GSTR STR?255,"flickering dimly"
	.GSTR STR?256,"dimly glowing"
	.GSTR STR?257,"glowing"
	.GSTR STR?258,"glowing brightly"
	.GSTR STR?259,"first"
	.GSTR STR?260,"second"
	.GSTR STR?261,"third"
	.GSTR STR?262,"home"
	.GSTR STR?263,"The dog-thing snaps at you viciously, and succeeds. Your head, it seems, is only a small mouthful for the poor animal, who is just as hungry afterward."
	.GSTR STR?264,"An insipidly grinning three-headed dog is wagging its tail here. It is wearing a huge dog collar."
	.GSTR STR?265,"Cerberus tears you limb from limb! What ferocity!"
	.GSTR STR?266,"That wasn't such a good idea. The creature was enjoying being your pet. As you unfasten the collar, the disappointed monster hound begins to growl, and then its three fang-crammed mouths rend you into little doggy biscuits."
	.GSTR STR?267,"Dragon hide is tough as steel, but you have succeeded in annoying him a bit. He looks at you as if deciding whether or not to eat you."
	.GSTR STR?268,"That captured his interest. He stares at you balefully."
	.GSTR STR?269,"The dragon is surprised and interested (for the moment)."
	.GSTR STR?270,"You've made him rather angry. You had better be very careful now."
	.GSTR STR?271,"That did no damage, but he turns his smoky yellow eyes in your direction and sighs."
	.GSTR STR?272,"incinerates you in a blast of white-hot dragon fire."
	.GSTR STR?273,"A huge ball of flame envelops you, but you don't even feel the heat. The dragon is puzzled, but not too puzzled to crush you in his jaws."
	.GSTR STR?274,"Worse for you, his mouth opens and a great gout of flame puffs out and consumes you on the spot."
	.GSTR STR?275,"The topiary animals attack! You are crushed by their branches and clawed by their thorns."
	.GSTR STR?276,"There is a large, white animal partly hidden behind some trees."
	.GSTR STR?277,"You catch a glimpse of something white between two hedges."
	.GSTR STR?278,"A unicorn is cropping grass on the other side of the room. A gold key hangs from a ribbon around its neck."
	.GSTR STR?279,"There is a beautiful unicorn eating roses here. Around his neck is a red satin ribbon on which is strung a tiny key."
	.GSTR STR?280,"There is a dishevelled and slightly unkempt princess here."
	.GSTR STR?281,"east"
	.GSTR STR?282,"west"
	.GSTR STR?283,"down"
	.GSTR STR?284,"up"
	.GSTR STR?285,"in"
	.GSTR STR?286,"out"
	.GSTR STR?287,"The door creaks open."
	.GSTR STR?288,"The door reluctantly closes."
	.GSTR STR?289,"You drop into the aquarium with a splash (which attracts the serpent). He greedily eats you. He's just a baby, after all, and needs all the food he can get."
	.GSTR STR?290,"Oh dear, you have cut yourself severely on the broken glass. I'm afraid you've bled to death."
	.GSTR STR?291,"The flask shatters, and poison gas fills the room!"
	.GSTR STR?292,"A shattered aquarium fills the northern half of the room."
	.GSTR STR?293,"I guess you were too careless."
	.GSTR STR?294,"He takes you instead. *Uurrp!*"
	.GSTR STR?295,"""Foolish mortal, if you insist..."" The demon crushes you with one blow of his enormous hand."
	.GSTR STR?296,"A dejected and fearful Wizard watches from the corner."
	.GSTR STR?297,"Most fine, master! But 'tis not enough. I will do a great service, and are not great services bought at great price?"
	.GSTR STR?298,"Very nice, but not enough!"
	.GSTR STR?299,"Ah, truly magnificent! Keep them coming."
	.GSTR STR?300,"Almost halfway there, oh worthy one!"
	.GSTR STR?301,"Oh, such beauty! Your generosity almost overwhelms me!"
	.GSTR STR?302,"Truly I shall do thee a wonderful service when thou hast finished!"
	.GSTR STR?303,"Truly you are most generous! But still, this is yet not enough."
	.GSTR STR?304,"A fine gift, mighty one, you have almost reached my fee."
	.GSTR STR?305,"Wondrous fine, master! But one treasure is yet to be given!"
	.GSTR STR?306,"You plunge to the bottom of the shaft as the spell wears off."
	.GSTR STR?307,"As the spell wears off, you find yourself making a half-gainer towards the bottom of the volcano."
	.GSTR STR?308,"You plummet to the bottom of the shaft."
	.GSTR STR?309,"You make a rather messy swan dive to the bottom of the volcano."
	.GSTR STR?310,"Feeble"
	.GSTR STR?311,"Fumble"
	.GSTR STR?312,"Fear"
	.GSTR STR?313,"Filch"
	.GSTR STR?314,"Freeze"
	.GSTR STR?315,"Fall"
	.GSTR STR?316,"Ferment"
	.GSTR STR?317,"Fierce"
	.GSTR STR?318,"Float"
	.GSTR STR?319,"Fireproof"
	.GSTR STR?320,"Fence"
	.GSTR STR?321,"Fantasize"
	.GSTR STR?322,"All at once you feel very tired."
	.GSTR STR?323,"You look at the Wizard in terror. You scramble away, trying to get as far as possible from him."
	.GSTR STR?324,"Your limbs suddenly feel like they have turned to stone. You can't move a muscle."
	.GSTR STR?325,"You begin to feel lightheaded."
	.GSTR STR?326,"You rush at the Wizard, intending to tear him limb from limb."
	.GSTR STR?327,"You feel more energetic now."
	.GSTR STR?328,"You suddenly decide that the Wizard isn't that terrifying..."
	.GSTR STR?329,"Your little finger begins to twitch, and then your whole body is free again."
	.GSTR STR?330,"Your head is clearer now."
	.GSTR STR?331,"You feel cooler and less angry now."
	.GSTR STR?332,"You sink quietly down again."
	.GSTR STR?333,"The Wizard snatches the wand away, muttering the word ""Float"" at the robot. Unfortunately he has no floating-point processor and dies in a vain attempt to divide 4.85 by 3.62."
	.GSTR STR?334,"The wand was still recharging from its last use. It discharges magic all over everything. You turn into a toad, the room fills with a fetid smell, and all sorts of other grubby things happen. Then the wand explodes!"
	.GSTR STR?335,"sparsely furnished and almost monkish in its austerity."
	.GSTR STR?336,"an opulently furnished seraglio out of an Arabian folktale."
	.GSTR STR?337,"decorated in the Louis XIV style."
	.GSTR STR?338,"overhung with palm-trees and lianas. The only furniture is a hammock."
	.GSTR STR?339,"constructed of delicate and wispy cloud-stuffs."
	.GSTR STR?340,"furnished in plastic and metal and looks like the control deck of a spaceship."
	.GSTR STR?341,"a suburban bedroom out of the 1950's, complete with bunk beds."
	.GSTR STR?342,"a dank and dimly lighted cave, its floor piled with furs and old bones."
	.GSTR STR?343,"You execute a perfect swan-dive into the depths below."
	.GSTR STR?344,"pile of jewels"
	.GSTR STR?345,"gold ingot"
	.GSTR STR?346,"basilisk"
	.GSTR STR?347,"bulging chest"
	.GSTR STR?348,"yellow sphere"
	.GSTR STR?349,"grue"
	.GSTR STR?350,"convention of wizards"
	.GSTR STR?351,"copy of ZORK I"

	.ENDI
